# Use postgres/example user/password credentials
version: '3.1'

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  postgres-data:
    name: postgres-data

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fasify-todolist-auth-ts-v2
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - 8080:8080

  app:
    container_name: app
    build: .
    image: pnywise/fastify-todolist-auth-ts-v2:2.0.0
    restart: always
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      APP_NAME: fastify-todolist-auth-ts-v2
      APP_SECRET:
      APP_PORT: 3000
      # database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: fasify-todolist-auth-ts-v2
